l = [
    {
        'reviewer_name' :'Michelle Isenberg', # 0
        'amount_of_reviews': '27 მიმოხილვა', #1
        'review_score': '5/5',#2
        'date': '5 თვის წინ',#3
        'posted_in': 'Google',#4
        '-ში',#5
        'review_content': '(თარგმნილია Google-ის მიერ) სასტუმროში ერთი ღამე ორნი ვიყავით და სრულიად კმაყოფილები დავრჩით!',
                          'ოთახი მართლაც ძალიან დიდია, ძალიან ლამაზად მოწყობილი და სუფთა. …',
        #6
        'სხვა',#7
        '1',#8
        'გაზიარება',#9

        'replied_by': 'მფლობელის პასუხი 5 თვის წინ', #10
        'reply_content': ['(თარგმნილია Google-ის მიერ) Ohhhh Michelle, du machst uns glücklich mit deinem Feedback.',
        'Und du hast das richtig gesehen, wir stellen unser Team - insbesondere an der Rezeption- grade neu zusammen. Alle hoch motiviert und offensichtlich konzentriert ;) danke für dein Verständnis und wir freuen uns dich bald wieder begrüßen zu dürfen.',

        '',
        'Herzlichen Gruß aus dem Aspria,', 'Sandra Schmalzried', 'Მთავარი მენეჯერი',
        '',
        '(ორიგინალი)',
        'Ohhhh Michelle, du machst uns glücklich mit deinem Feedback.',
        'Und du hast das richtig gesehen, wir stellen unser Team - insbesondere an der Rezeption- grade neu zusammen. Alle hoch motiviert und offensichtlich konzentriert ;) danke für dein Verständnis und wir freuen uns dich bald wieder begrüßen zu dürfen.',
        '',
        'Herzlichen Gruß aus dem Aspria,',
        'Sandra Schmalzried',
        'General Manager']
},
    [
        'Karin Bugge',
        '25 მიმოხილვა',
        '5/5',
        '2 თვის წინ',
        'Google',
        '-ში',
        '(თარგმნილია Google-ის მიერ) ძალიან სასიამოვნო მიღება და ფიტნეს სტუდიის ტური იყო ძალიან სასიამოვნო.',
        'მე და ჩემმა შეყვარებულმა მაშინვე გადავწყვიტეთ ხელშეკრულების გაფორმება. …',
        'სხვა',
        'მოწონება',
        'გაზიარება',
        'მფლობელის პასუხი 2 თვის წინ',
        '(თარგმნილია Google-ის მიერ) მოხარულნი ვართ, რომ ჩვენმა სერვისმა კარგი შთაბეჭდილება დატოვა. კეთილი იყოს თქვენი მობრძანება ასპრიაში,',
        'სანდრა შმალზრიედი',
        'Მთავარი მენეჯერი',
        '',
        '(ორიგინალი)',
        'Wir freuen uns, dass unser Service einen bleibenden guten Eindruck hinterlassen hat. Herzlich willkommen bei uns im Aspria,',
        'Sandra Schmalzried',
        'General Manager'

],


    ['Alina', '1 მიმოხილვა', '1/5', '5 თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) შაბათიდან კვირამდე აქ ვიყავით ბავშვთან ერთად (4 თვე). საუზმე კატასტროფა იყო ფასისთვის! თონეში უკეთესობისკენ შეგეძლო. თავხედობა!!! წინა მაგიდაც საკმაოდ გადატვირთული დაგვხვდა და ამას ძალიან დიდი დრო დასჭირდა. …', 'სხვა', '3', 'გაზიარება', 'მფლობელის პასუხი 5 თვის წინ', '(თარგმნილია Google-ის მიერ) გამარჯობა ალინა, უპირველეს ყოვლისა გმადლობთ, რომ დრო დაუთმეთ და გვითხარით თქვენი შთაბეჭდილებები.', 'ძალიან ვწუხვარ, რომ ჩვენ ნამდვილად ვერ გავამართლეთ თქვენი მოლოდინი ჩვენი ფიტნეს და გამაჯანსაღებელი სასტუმროთ. ჩვენ ვაფიქსირებთ თქვენს ქულებს და სიამოვნებით ვამოწმებთ მათ ოპტიმიზაციის ვარიანტებისთვის.', '', 'Საუკეთესო სურვილებით', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', '', '(ორიგინალი)', 'Hallo Alina, erstmal danke für die Zeit uns eure Eindrücke zu schildern.', 'Tut mir sehr leid, dass wir mit unserem Fitness- und Wellness Hotel nicht wirklich euren Erwartungen gerecht werden konnten. Eure Punkte nehmen wir auf und prüfen diese gerne bzgl. Optimierungsmöglichkeiten.', '', 'Mit den besten Grüßen', 'Sandra Schmalzried', 'General Manager'], ['Ka Ba', '7 მიმოხილვა', '4/5', '3 თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) იქ პირველად ვიყავი. ძალიან ლამაზი თანამედროვე დაწესებულება, კარგი პერსონალი, საუკეთესო ფიტნეს დარბაზი და მასაჟი ასევე ძალიან კარგი იყო. მთლიანობაში კარგი კონცეფციაა და ადგილი, სადაც უნდა წახვიდე, როცა შესვენება …', 'სხვა', 'მოწონება', 'გაზიარება', 'მფლობელის პასუხი 3 თვის წინ', '(თარგმნილია Google-ის მიერ) ოჰჰჰჰ, ჩვენ გავარკვევთ, არის თუ არა ამის გამოსავალი.', '', 'გმადლობთ სასიამოვნო დეტალური გამოხმაურებისთვის,', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', 'ასპრია ბერლინი', '', '(ორიგინალი)', 'Ohhhhh, wir machen uns schlau, ob es hierfür ne Lösung gibt.', '', 'Vielen Dank für das schöne ausführliche
Feedback,', 'Sandra Schmalzried', 'General Manager', 'Aspria Berlin'], ['Gerry Rome', '6 მიმოხილვა', '2/5', 'ერთი თვის წინ', 'Google', '-ში', "Just to make it clear I am writing a review on the gym and not the hotel. I have been a gym member for the past two years. I became a member because the manager insured me that they don't allow aggressive people to enrol. Two years after …", 'სხვა', '2', 'გაზიარება', 'მფლობელის პასუხი 4 კვირის წინ', '(თარგმნილია Google-ის მიერ) საღამო მშვიდობისა გერი, გმადლობთ მიმოხილვისთვის და თქვენი შეშფოთებისთვის. ძალიან ვწუხვარ, რომ
თქვენ განიცადეთ სიტუაციები, რამაც დისკომფორტი შეგაწუხათ. მე და ჩემი გუნდი სამუშაო საათებში ადგილზე ვართ და სიამოვნებით მივიღებთ პირდაპირ რჩევას. რა თქმა უნდა, სამწუხაროა, რომ ჩვენს სახლში არის რამდენიმე წევრი, რომლებიც არ იცავენ კლუბურ ეტიკეტს და მადლობელი იქნებიან ნებისმიერი ინფორმაციისთვის. დღე და დრო საკმარისია თქვენი ქულების განსახორციელებლად, რათა შემცირდეს ცალკეული პირები/ჯგუფები. მე და ჩემი გუნდი მოხარული ვიქნებით დაგელაპარაკებით პირადად და მადლობელი ვიქნებით, თუ გამოიყენებთ შესაძლებლობას და დატოვოთ უფრო კონკრეტული ინფორმაცია წევრობის სერვისში ან ელექტრონული ფოსტით: blnmemberservice@aspria.de ან მენეჯმენტი Sandra Schmalzried, რადგან
ბოლო რამდენიმე თვე იყო მცირე ან საერთოდ არ ყოფილა კონკრეტული გამოხმაურება თქვენ მიერ აღნიშნულ საკითხებზე.', 'თუმცა, მე ასევე შევნიშნე დადებითი ასპექტები და გმადლობთ, რომ ახსენეთ ისინი თქვენს გამოხმაურებაში. დარწმუნებული არ ვარ, ვინ მოგცათ გარანტია წინასწარ იდენტიფიცირება და უარყო წევრები, რომლებიც არასწორად იქცევიან, მაგრამ შემიძლია დაგარწმუნოთ, რომ ჩვენ მივყვებით ნებისმიერ მითითებებს, რათა მივცეთ ჩვენი წევრები და სტუმრები კლუბში დასასვენებლად.', '', 'ასპრიას თბილი მოკითხვით', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', '', '(ორიგინალი)', 'Einen schönen guten Abend Gerry, vielen Dank für Ihre Rezension und Äußern Ihrer Bedenken. Es tut mir sehr leid, dass Sie Situationen erlebten, die bei Ihnen Unbehagen ausgelöst haben. Mein Team und ich sind während der Öffnungszeiten vor Ort und nehmen gerne direkt
Hinweise entgegen. Natürlich ist es bedauerlich, dass es vereinzelt Mitglieder in unserem Hause gibt, die sich wohl nicht an die Etikette des Clubs halten und sind hier für jeden Hinweis dankbar. Es reicht Tag und Uhrzeit aus um Ihren Punkten
nachzugehen um die einzelnen Personen / -gruppen einzugrenzen. Mein Team und ich
würden uns sehr gerne persönlich mit Ihnen unterhalten und wären Ihnen sehr verbunden, wenn Sie die Möglichkeit nutzen, konkretere Infos beim Membership Service oder per email: blnmemberservice@aspria.de oder Management Sandra Schmalzried zu hinterlassen, da in den letzten Monaten zu den von Ihnen genannten Punkten kaum bis gar keine konkreteren Rückmeldungen eingegangen sind. ', 'Durchaus habe ich aber auch die positiven Aspekte wahrgenommen und danke Ihnen, dass Sie diese in Ihrem Feedback nicht unerwähnt lassen. Ich bin mir nicht sicher, wer Ihnen die Sicherheit gegeben hat, Mitglieder ohne Benehmen vorab zu erkennen und den Zutritt zu verwehren, kann Ihnen aber versichern, dass wir jedem Hinweis nachgehen um unseren Mitgliedern und Gästen im Club einen Ort der Entspannung zu bieten. ', '', 'Mit
einem herzlichen Gruß aus dem Aspria', 'Sandra Schmalzried', 'General Manager'],
['Nici Theuerkauf', '3 მიმოხილვა', '1/5', '2 თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) სირცხვილია, ყველაფერი, რისთვისაც ეს კლუბი ოდესღაც იდგა, წავიდა. მართლაც კარგი მასწავლებლები იყვნენ და კურსების საოცარი სპექტრი, ახლა საკმაოდ
საშუალოა. აუდიტორია ძალიან პროლეტარულია... გაშტერებული, ამაზრზენი …', 'სხვა', '5', 'გაზიარება', 'მფლობელის პასუხი 2 თვის წინ', '(თარგმნილია Google-ის მიერ) ძვირფასო ქალბატონო თეუერკაუფ, ჩვენ ძალიან სერიოზულად ვითვალისწინებთ ინფორმაციას ჩვენი წევრებისა და სტუმრებისგან, როგორც კი ის ეცნობება წევრების სამსახურებს ან ხელმძღვანელობას ან გახდება ცნობილი. საუნის ოსტატები ადგილზე არიან პირდაპირი საჩივრების მისაღებად. თუმცა, ჯერჯერობით, ჩვენ არ მიგვიღია რაიმე გამოხმაურება თქვენი დაკვირვების შესახებ. იმისათვის, რომ ვიმოქმედოთ, სასწრაფოდ გვჭირდება მეტი ინფორმაცია. გთხოვთ
დაუკავშირდეთ ჩვენი წევრების სერვისს აქ კლუბში.', '', 'გმადლობთ გამოხმაურებისთვის
და ძალიან ვწუხვართ, რომ კლუბი აღარ პასუხობს თქვენს მოლოდინებს და იდეებს და რომ საუნაში თქვენი ყოფნა შეფერხდა.', '', 'ძალიან დიდი მადლობა', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', '', '(ორიგინალი)', 'Sehr geehrte Frau Theuerkauf, wir nehmen Hinweise unserer Mitglieder und Gäste sehr ernst, sobald es dem Mitgliederservice oder dem Management zugetragen wird bzw. zur Kenntnis gelangt. Saunameister sind vor Ort um direkte Beschwerden entgegen zu nehmen. Bisher wurde uns jedoch zu Ihren Beobachtungen noch keine Rückmeldungen gegeben. Um agieren zu können benötigen
wir dringend mehr Informationen. Bitte wenden Sie sich doch an unseren Mitgliederservice hier im Club.', '', 'Wir danken für Ihre Rückmeldung und bedauern es sehr, dass der Club nicht mehr Ihren Erwartungen und Vorstellungen entspricht und Ihr Saunaaufenthalt gestört worden ist.', '', 'Herzlichen Dank', 'Sandra Schmalzried', 'General Manager'], ['Sabine hamburg', '5 მიმოხილვა', '2/5', '5 თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) საცურაო აუზი რემონტის პროცესში იყო, მაგრამ სწორედ ამიტომ დავჯავშნე სასტუმრო. დაგვიანებით გადახდა არ გადაირიცხა, სამაგიეროდ, უხეში სატელეფონო ზარი მივიღე. ხედი ოთახიდან: ბინძური სახურავი სიგარეტის ნამწვით. საუზმე …', 'სხვა', '2', 'გაზიარება'], ['A S', '22 მიმოხილვა', '2/5', '4 თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) მისაღების პერსონალი არ არის
ძალიან მეგობრული. ოთახში ერთი საწოლი ახალი არ იყო, როცა შევედით.', 'ხელის საპონი
ცარიელი იყო. სახის ქსოვილები არ იყო შევსებული, მიუხედავად იმისა, …', 'სხვა', '3', 'გაზიარება'], ['Tarik Yakar', 'Local Guide · 59 მიმოხილვა', '2/5', 'ერთი კვირის
წინ', 'Google', '-ში', 'ᲡᲘᲐᲮᲚᲔ', '(თარგმნილია Google-ის მიერ) ასე რომ, მე ვიხდი 145 ევროს, შემდეგ კი მიწისქვეშა ავტოსადგომისა და დამატებითი პირსახოცების ხარჯებს.
აქ თქვენ ხართ სასმელების მოხმარებით 200 € თვეში. …', 'სხვა', '2', 'გაზიარება', 'მფლობელის პასუხი 6 დღის წინ', '(თარგმნილია Google-ის მიერ) ძვირფასო ბატონო იაკარ,', 'გმადლობთ გამოხმაურებისთვის. მოხარული ვარ, რომ მივიღო თქვენი წინადადებები გაუმჯობესების პოტენციალის შესახებ. დახურვის პერიოდში (7 თვეზე მეტი) იყო გაურკვევლობის
მაღალი ხარისხი, როდის, თუ საერთოდ და რამდენად შესაძლებელი იქნებოდა ხელახლა გახსნა. მაგრამ წელს ჩვენ უკვე განვახორციელეთ ინვესტიცია ახალ ფუნქციურ გარე ზონაში, ახალ აღჭურვილობაში ჩვენი პოპულარული კურსებისთვის Loft1-ში და მცირე აღჭურვილობა სასწავლო ოთახებისთვის და ა.შ.', 'ჩვენი რესტორანი ასევე გარემონტდა და შეიქმნა სამუშაო დარბაზი, რათა ჩვენს წევრებს შესთავაზოთ დამატებითი დამატებითი ღირებულება აქაც.', 'მოხარული ვიქნებით, თუ განაგრძობთ ასპრიას, როგორც თქვენი სასიამოვნო კლუბის გამოყენებას.', '', 'Საუკეთესო სურვილებით', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', 'ასპრია ბერლინი', '', '(ორიგინალი)', 'Sehr geehrter Herr Yakar,', 'Wir danken für Ihr Feedback. Gerne nehme ich Ihre Anregungen bzgl Verbesserungspotential entgegen. Während der Schließzeit (über 7 Monate) herrschte eine hohe Ungewissheit wann, ob überhaupt und in welchem Umfang wieder aufgemacht werden kann. Doch haben wir dieses Jahr bereits in einen neuen Functional Außenbereich, neues Equipment für unsere beliebten Kurse in Loft1 sowie Kleinequipment für Trainingsräume investiert usw.', 'Auch sind unsere Restaurant erneuert und eine Worklounge geschaffen worden um unseren Mitgliedern auch hier einen zusätzlichen Mehrwert zu bieten.', 'Wir würden uns freuen, wenn Sie Aspria auch weiterhin als Ihren Wohlfühlclub nutzen.', '', 'Mit besten Grüßen', 'Sandra Schmalzried', 'General Manager', 'Aspria Berlin'], ['Nadine', '3 მიმოხილვა', '2/5', '2 დღის წინ', 'Google', '-ში', 'ᲡᲘᲐᲮᲚᲔ', '(თარგმნილია Google-ის მიერ) შაბათ-კვირას 2 ღამე ბერლინში ვიყავი სამუშაოდ და ამჯერად ასპრია ავირჩიე სპორტული და საუნა.', 'როცა საღამოს 6 საათზე ცოტა ხანში მივედი, პირველი, რაც დამხვდა, იყო შეტყობინება, …', 'სხვა', 'მოწონება', 'გაზიარება'], ['Andreas Deppert', 'Local Guide · 124 მიმოხილვა', '3/5', '4 თვის წინ', 'Google', '-ში',
'(თარგმნილია Google-ის მიერ) ფიტნეს კლუბი სასტუმროთ', 'თუ ჩვენ მსგავსად გიყვართ შვებულებაში ვარჯიში, ბანაობა და საუნაში გასეირნება, ასპინა იდეალურია. მართლაც დიდი. ადგილმდებარეობა ასევე კარგია. …', 'სხვა', '2', 'გაზიარება'], ['Dieter H.', 'Local Guide · 126 მიმოხილვა', '5/5', '3 თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) შეუძლია დაადასტუროს (თითქმის) ყველა დადებითი მიმოხილვა და არ სურს ტექსტის გამეორება. ასპრიაში ორი ღამე დავრჩით და ჩვენი მოლოდინი არამარტო გამართლდა,
არამედ გადააჭარბა. ჩვენ განსაკუთრებით მომეწონა სასიამოვნო და …', 'სხვა', 'მოწონება', 'გაზიარება', 'მფლობელის პასუხი 3 თვის წინ', '(თარგმნილია Google-ის მიერ) Ვაუ! დიდი მადლობა ამ კარგი გამოხმაურებისთვის... ჩვენ დავრჩებით ბურთზე და მოუთმენლად ველით შემდეგ ჯერს.', '', 'პატივისცემით,', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', '', '(ორიგინალი)', 'Wow! Herzlichen Dank für dieses schöne Feedback…wir bleiben
am Ball und freuen uns auf ein nächstes Mal.', '', 'Herzlichst,', 'Sandra Schmalzried', 'General Manager'], ['Oliver Bauer', 'Local Guide · 33 მიმოხილვა', '4/5',
'ერთი თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) გამარჯობა,', '', 'ჩვენ იქ ვიყავით 4 დღე, უნდა ითქვას, რომ კარგი სასტუმრო იყო, განსაკუთრებით თუ …',
'სხვა', '0:20', '+', '5', 'მოწონება', 'გაზიარება', 'მფლობელის პასუხი ერთი კვირის
წინ', '(თარგმნილია Google-ის მიერ) ძვირფასო ბატონო ფერმერი,', 'დიდი მადლობა თქვენი გამოხმაურებისთვის და კეთილი სიტყვებისთვის.', '', 'ამასობაში ჩვენ შევეცადეთ გაგვერკვია, რატომ დაირღვა თქვენი ღამის ძილი, მაგრამ მომდევნო დღეებში ხმაური ვერ აღმოვაჩინეთ. მაგრამ რა თქმა უნდა დააკვირდით მას. მიუხედავად ამისა, მინდა გამოვხატო ჩემი სინანული, რომ სამწუხაროდ ამან იმოქმედა თქვენს ძილზე.', '', 'ჩვენ ყველაფერს ვაკეთებთ იმისათვის, რომ შევინარჩუნოთ და დავარწმუნოთ ან გავაუმჯობესოთ ჩვენი სერვისი :)', '', 'Საუკეთესო სურვილებით,', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', 'ასპრია
ბერლინი', '', '(ორიგინალი)', 'Sehr geehrter Herr Bauer,', 'herzlichen Dank für Ihre Rückmeldung und die netten Worte.', '', 'Wir haben zwischenzeitlich versucht herauszufinden warum Ihre Nachtruhe gestört wurde, konnten aber in den Folgetagen
kein Geräuschaufkommen feststellen. Beobachten das aber natürlich weiter. Nichtsdestotrotz möchte ich mein Bedauern ausdrücken, dass dies Ihren Schlaf leider beeinflusst hat.', '', 'Wir geben unser Bestes unseren Service aufrecht zu halten und zu überzeugen bzw. zu verbessern:)', '', 'Mit allerbesten Grüßen,', 'Sandra Schmalzried', 'General Manager', 'Aspria Berlin'], ['D Tr', 'Local Guide · 12 მიმოხილვა', '2/5', 'ერთი თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) სამწუხაროდ, ასპრია აღარ არის ისეთი, როგორიც იყო პანდემიამდე.', 'როგორც ქალი, საუნაში და ვარჯიშის დროს თავს კომფორტულად აღარ გრძნობ, რადგან …', 'სხვა', '4', 'გაზიარება', 'მფლობელის პასუხი 4 კვირის წინ', '(თარგმნილია Google-ის მიერ) ძვირფასო ქალბატონო D Tr, მენეჯმენტი ძალიან მოხარული იქნებოდა, თუ პირდაპირ გაზიარებდით თქვენს დაკვირვებებს, რადგან ჩვენთვის ყველაზე მნიშვნელოვანია, რომ ჩვენი წევრები კომფორტულად გრძნობდნენ თავს და ივარჯიშონ მშვიდად. სამწუხაროდ, ხელმძღვანელობამ არ იცის რაიმე მუდმივი საჩივარი. მიუხედავად ამისა, მე ვკითხე ჩემს გუნდებს მათი გამოხმაურების შესახებ და დავავალე მათ, გთხოვთ, თვალყური ადევნონ გამოხმაურებას და მომეხსენებინათ. ეს ასევე იქნებოდა უფრო პროდუქტიული ალტერნატივა იმ დიდი ხნის თანამშრომლებისთვის, რომლებთანაც თქვენ ისაუბრეთ, რადგან შეიძლება იყვნენ წევრები, რომლებიც არ იცავენ კლუბის ეტიკეტს და სიამოვნებით მივიღებთ უფრო კონკრეტულ ინფორმაციას. წევრობის სერვისის გუნდი ან მე - სანდრა შმალზრიედი - როგორც მენეჯმენტი, სიამოვნებით დაგეხმარებით. ნებისმიერ შემთხვევაში, გისურვებთ სასიამოვნო დასვენების დღეს ჩვენს კლუბში და თქვენს განკარგულებაში ვარ პირადი საუბრისთვის.', 'სალამი', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', 'ასპრია ბერლინი', '', '(ორიგინალი)', 'Sehr geehrte Frau D Tr, das Management hätte sich sehr gefreut, wenn Sie Ihre Beobachtungen direkt weitergegeben hätten, da uns am meisten daran gelegen ist, dass unsere Mitglieder sich wohl fühlen
und entspannt trainieren können. Leider ist dem Management nichts bekannt von permanenten Beschwerden. Nichts desto trotz habe ich meine Teams zu Ihrer Rückmeldung befragt und beauftragt, Feedback bitte nachzugehen und es mir zu melden. Das wäre auch die produktivere Alternative gewesen der langjährigen Mitarbeiter mit denen Sie sich unterhalten haben, denn es mag durchaus Mitglieder geben, die sich nicht an die Etikette des Clubs halten und dann würden wir uns über konkretere Hinweise freuen. Gerne steht Ihnen hierfür das Membership Service Team oder ich - Sandra Schmalzried - als Management zur Verfügung. Ich wünsche Ihnen auf jeden Fall
noch ein paar schöne entspannte Tage in unserem Club und stehe Ihnen gerne für ein persönliches Gespräch zur Verfügung,', 'herzlichen Gruß', 'Sandra Schmalzried', 'General Manager', 'Aspria Berlin'], ['K. Franz W.', 'Local Guide · 455 მიმოხილვა', '5/5', '5 თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) უზარმაზარი პირველი კლასის სპა სასტუმრო,', 'არამედ კურფურსტენდამთან ახლოს მდებარეობის გამო (დაახლოებით 300 მ),', 'ჩაქუჩი "ღირშესანიშნაობების სასტუმრო". …', 'სხვა', '+', '5', '1', 'გაზიარება'], ['Kai Reuter', '9 მიმოხილვა', '1/5', '3 თვის წინ', 'Google',
'-ში', '(თარგმნილია Google-ის მიერ) დღეს წავედით DaySpa-ში ასპირაში. უკაცრავად, მაგრამ 60 ევროსთვის ნამდვილად მეტს ველოდით. აქ არც ხალათებია და არც ჩუსტები. წყალი არ არის საუნის შემდეგაც, შეგიძლიათ შეიძინოთ ბისტროში. ასე რომ, რამდენიმე საუნისთვის, …', 'სხვა', '5', 'გაზიარება', 'მფლობელის პასუხი 3 თვის წინ', '(თარგმნილია Google-ის მიერ) გმადლობთ გამოხმაურებისთვის და შთაბეჭდილებების გაზიარებისთვის. ვწუხვარ, რომ თქვენ ვერ შეძელით კლუბის სრულად გამოყენება თქვენს დღეს და რომ სტარტი უკვე დატვირთული იყო.', '', 'ასპრია არის ჰოლისტიკური კეთილდღეობის კლუბი და არაწევრებისთვის 60 ევრო დღიური ბილეთი მოიცავს ჩვენს საუნას სახურავის ტერასით, ასევე 25 მეტრიანი გახურებული აუზის გამოყენებას, ფიტნეს ზონებს და კურსებს ჩვენი შეთავაზებების ფართო სპექტრიდან. ასევე შესაძლებელია თქვენი ყოფნის კომბინირება მასაჟთან, მაგალითად.', '', 'ჩვენ გვაქვს მეტი ინფორმაცია ამის შესახებ ჩვენს ვებსაიტზე, მოხარული ვიქნებით გადავამოწმოთ, ასახავს თუ არა ეს ჩვენს შეთავაზებას შესაბამისად.', '', 'Საუკეთესო სურვილებით', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', 'ასპრია ბერლინი', '', '(ორიგინალი)', 'Vielen Dank für die Rückmeldung und Schilderung Ihrer Eindrücke. Es
tut mir leid, dass Sie den Club nicht in seiner vollen Gänze an Ihrem Tag nutzen
konnten und der Start schon holprig war.', '', 'Das Aspria ist ein ganzheitlicher Wellbeing Club und in den 60€ Tageseintritt für Nicht-Mitglieder ist unter anderem auch unser Saunabereich mit Dachterrasse inklusive, aber auch die Nutzung des
beheizten 25 Meter Pool, die Fitnessflächen und Kurse unseres vielfältigen Angebots. Außerdem ist es möglich den Aufenthalt noch mit z.B. einer Massage zu kombinieren.', '', 'Auf unserer Webseite haben wir dazu mehr Informationen, gerne prüfen wir hier nochmal ob diese unser Angebot entsprechend wiedergibt.', '', 'Mit besten Grüßen', 'Sandra Schmalzried', 'General Manager', 'Aspria Berlin'], ['Ti nella', '15 მიმოხილვა', '3/5', '2 კვირის წინ', 'Google', '-ში', 'ᲡᲘᲐᲮᲚᲔ', '(თარგმნილია Google-ის მიერ) საკმაოდ კარგია, მაგრამ:', '- მიმღებები ცოტათი გადატვირთულები იყვნენ და საქმის გარკვევას დიდი დრო დასჭირდათ. …', 'სხვა', 'მოწონება', 'გაზიარება',
'მფლობელის პასუხი ერთი კვირის წინ', '(თარგმნილია Google-ის მიერ) დიდი მადლობა თქვენი კონსტრუქციული გამოხმაურებისთვის.', 'ნებისმიერ შემთხვევაში, ჩვენ დავაბრუნებთ თქვენს ქულებს და მასთან დაკავშირებულ სტანდარტებს კლუბში/სასტუმროში, რათა გავაუმჯობესოთ ნებისმიერი პროცესი.', 'ადგილზე არსებული კოლეგები ხელმისაწვდომია პირდაპირი კომენტარებისთვის და თხოვნით, რომ დაეხმარონ პირდაპირ ან იპოვონ ალტერნატივა (მასაჟის მოთხოვნა, ხალათები, ახალი კვერცხის კერძები, საუზმე ბუფეტი...).', 'იქნებ დაგარწმუნოთ თქვენი შემდეგი ყოფნისას.', '', 'პატივისცემით,', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', 'ასპრია ბერლინი', '', '(ორიგინალი)', 'Wir danken sehr für Ihr konstruktives Feedback.', 'Wir setzen auf jeden Fall Ihre Punkte und die dazu gehörigen Standards im Club/Hotel nochmal auf den Prüfstand, um eventuell Prozesse zu verbessern.', 'Die Kollegen vor Ort stehen für direkte Anmerkungen und Wünsche gerne zur Verfügung um direkt zu helfen oder eine Alternative zu finden (Massagewünsche, Bademäntel, frische Eierspeisen Frühstücksbuffet…).', 'Vielleicht dürfen wir Sie bei Ihrem nächsten Aufenthalt überzeugen.', '', 'Herzlichst,', 'Sandra Schmalzried', 'General Manager', 'Aspria Berlin'], ['Andreas von Richter', '2 მიმოხილვა', '3/5', 'ერთი თვის წინ', 'Google', '-ში', '(თარგმნილია Google-ის მიერ) სამწუხაროა, რომ ნამდვილად კარგი
სასტუმრო და სპორტული კლუბია, მაგრამ Mgmt. არ არის ზუსტად მომხმარებელზე მეგობრული. სამი ღამის შემდეგ (გადარიცხვა 500 ევროზე მეტი) კიდევ ერთი საათით ოთახში 13:00 საათამდე; 12.5 ევრო …', 'სხვა', 'მოწონება', 'გაზიარება', 'მფლობელის პასუხი 4 კვირის წინ', '(თარგმნილია Google-ის მიერ) ძვირფასო ბატონო ფონ რიხტერ, მოხარული ვართ, რომ ჩვენი შეთავაზება "ტექნიკასთან" დაკავშირებით თქვენთვის შესაფერისია და თქვენ ხართ სტუმარი ჩვენს სასტუმროსა და კლუბში. რაც შეეხება დაგვიანებულ შემოწმებას, ვწუხვარ, რომ ჩვენ არ შეგვიძლია შემოგთავაზოთ ეს სრულიად უფასოდ. პირველი საათი, რა თქმა უნდა, უფასოა, ჩვეულებრივ გასვლა 11:00 საათზე და უფასო გაგრძელება 12:00 საათამდე მოთხოვნით. საკომისიო 25 ევრო მოქმედებს სასურველი გასვლისთვის 14:00 საათამდე. ვიმედოვნებთ, რომ ჩვენს კლუბში არსებული ატმოსფერო და უფასო სპორტი და გამაჯანსაღებელი შეთავაზებები დადებითად დაასრულებს თქვენს ყოფნას.', '', 'სალამი', 'სანდრა შმალზრიედი', 'Მთავარი მენეჯერი', 'ასპრია ბერლინი', '', '(ორიგინალი)', "Sehr geehrter Herr Von Richter, wir freuen uns, dass unser Angebot in Bezug auf die 'Hardware' Ihnen entgegenkommt und Sie Gast in unserem Hotel und Club sind. Es tut mir leid, dass wir bzgl. einem späten Check-out dies nicht komplett ohne Aufpreis anbieten können. Die erste Stunde ist natürlich kostenfrei, generell Check-out 11:00 Uhr und kostenfreie Verlängerung bis 12:00 Uhr auf Anfrage. Die Gebühr von 25€ fällt dann für einen gewünschten Check-out bis 14:00 Uhr an. Wir hoffen, dass aber das Ambiente und kostenfreie Sport- und Wellnessangebot in unserem Club Ihren Aufenthalt doch noch positiv abrundet. ", '', 'Herzlichen Gruß', 'Sandra Schmalzried', 'General Manager', 'Aspria Berlin'], ['Kana M.', '12 მიმოხილვა', '4/5', '2 დღის წინ', 'Google', '-ში', 'ᲡᲘᲐᲮᲚᲔ', 'The swimming pool is probably the best in town. Most of the staff are nice and helpful. Kids friendly facilities are big plus ! …', 'სხვა', 'მოწონება', 'გაზიარება']]
]